### ISSUE TITLE
python QAmodel/run.py --input QAmodel/example     error

### ISSUE THREAD

**Issue by lfs119** [Gonglab-THU/GDFold2#1]
Hi, python fold.py can run.
"python QAmodel/run.py --input QAmodel/example"   gets a segmentation fault(core dumped)

**Comment by Gonglab-THU** [comment]
Thank you for reaching out. The "Segmentation fault (core dumped)" error usually occurs due to invalid memory access. Since the program runs fine on my machine, the issue might be related to differences in the environment. Here are a few steps to help troubleshoot:
1. Try running the program on a clean environment to see if the issue persists.
2. The installation commands for torch-cluster and torch_scatter provided by us rely on pytorch version 1.12.1 and CUDA version 11.3. Please check whether you have installed pytorch, torch_geometric, torch-cluster and torch_scatter that correspond to the CUDA version.
